### ISSUE TITLE
Deno support

### ISSUE THREAD

**Issue by Any0ne22** [nimiq/core-js#590]
Will the Nimiq team consider adding a compatibility with Deno and building a Nimiq core Deno module ?

**Comment by sisou** [comment]
Hi, thanks for your interest!

@nimiq/core-js is on maintenance support only and will not receive any new features or major reworks (which would be required for Deno support). We are working on Nimiq 2.0 Albatross at the moment, which is completely written in Rust and developed here: https://github.com/nimiq/core-rs-albatross.

Since the next version of Nimiq is written in Rust, it likely has great synergy with Deno (also Rust-based), and integration opportunities between Nimiq and Deno will likely present themselves in the near future when we compile the Albatross code to WebAssembly.

If you have experience with native Deno plugins, we look forward to helping you integrate the Nimiq Albatross client. :+1:
